language: python
python:
  - "2.6"
  - "2.7"
env: PYTHONPATH=$PWD:$PYTHONPATH PATH=$PWD/bin:$PATH
# command to install dependencies
install: "pip install -r requirements.txt"
script: "echo $PYTHONPATH && ls -la && ezmomi --help"
