language: python
python:
  - "2.7"
env: PYTHONPATH=$PWD:$PYTHONPATH PATH=$PWD/bin:$PATH
# command to install dependencies
install:
  - "pip install -r requirements.txt"
script:
  - "ezmomi --help"
  - "python -m py_compile ezmomi/"
  - "pep8 ezmomi/"
